### ISSUE TITLE
タイトルが正しく取得されない

### ISSUE THREAD

**Issue by 844196** [844196/844196_renge#11]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">.<a href="https://twitter.com/844196">@844196</a> が「BibmHLv43Q」で抜いたん！ <a href="https://t.co/rWO5AF6gro">https://t.co/rWO5AF6gro</a></p>&mdash; $ bundle exec renge (@844196_renge) <a href="https://twitter.com/844196_renge/status/658047608531714048">2015, 10月 24</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

http://t.co/以下が渡されてるぽい

**Comment by sasairc** [comment]
@844196 
展開であれば、mikutterの`core/plugin/tco/tco.rb`辺りが参考になるかも。
https://github.com/mikutter/mikutter/tree/master/core/plugin/tco

**Comment by 844196** [comment]
@sasairc :eggplant: 

![09341c63](https://cloud.githubusercontent.com/assets/4990822/10714730/5a39db30-7b3f-11e5-9fa1-8aa64c6709d5.jpg)
