### ISSUE TITLE
定期実行間隔は適切か

### ISSUE THREAD

**Issue by 844196** [844196/844196_renge#5]
- 対話処理が可能になったため、サーバの死活監視だけで見ると別に定期実行いらないんじゃね？
- API切れが怖い

**Comment by 844196** [comment]
- `list-3`に編入させたが、TLが埋まるのも困る

**Comment by sasairc** [comment]
@844196 
レンタル鯖なら午前0時と正午の定期実行で十分では（安定してそうだし）

**Comment by 844196** [comment]
@sasairc 
`% yasuna`とは間隔ズレますがそれくらいですかね
メインで見てる`list-3`が埋まるのも困るので...

**Comment by sasairc** [comment]
@844196 
`% yasuna`は誤字検出と生存信号に加えて、私がやすなちゃん語録を見て心を洗われたいが為に動かしているので無理に合わせる必要はないですよ。

mikutter限定なら、生存信号にある種の文字列を付加しておいて、`list-3`の抽出タブで生存信号のみヒットさせても良さそうですが。

**Comment by 844196** [comment]
@sasairc 

> mikutter限定なら、生存信号にある種の文字列を付加しておいて、list-3の抽出タブで生存信号のみヒットさせても良さそうですが。

携帯や`tweetvim`で見る用に作ったリストなので、ミュート設定可能な端末前提にはしたくないという思いがあります。

とりあえず本件は、現行の30分おきから0時・12時へ定期実行間隔変更ということで、修正コミットの後クローズしたいと思います。

**Comment by sasairc** [comment]
@844196  
![default](https://cloud.githubusercontent.com/assets/9349287/10654873/782e32ea-78aa-11e5-87b4-026229af2f36.png)
:sa:
